markdown: redcarpet

baseurl: /liaison

pygments: true

redcarpet:
  extensions: ['tables']

keywords: ['Data binding', 'MVC', 'MV*', 'JavaScript', 'Object.observe', 'Array.observe', 'shim', 'Web Components', 'Standards']
